### ISSUE TITLE
`bottle :unneeded` deprecated

### ISSUE THREAD

**Issue by thomvil** [koyeb/homebrew-tap#1]
Homebrew signals the deprecation of the `unneeded` flag.

````
Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the koyeb/tap tap (not Homebrew/brew or Homebrew/core):
  /opt/homebrew/Library/Taps/koyeb/homebrew-tap/Formula/koyeb.rb:9
````

**Comment by bchatelard** [comment]
Thanks for the report!

We are using goreleaser to generate this, this should be fixed by https://github.com/goreleaser/goreleaser/issues/2595

I think it should be fixed on next release of koyeb-cli

**Comment by remyleone** [comment]
@bchatelard any update on this? :) I think it was merged in goreleaser.

**Comment by bchatelard** [comment]
This should be fixed with latest release
